# Generated by Django 2.2.1 on 2019-06-03 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profesor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesor',
            name='delete',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='edited',
        ),
    ]
